### ISSUE TITLE
Broken Chunk-Splitting in Rollup

### ISSUE THREAD

**Issue by LorisSigrist** [opral/inlang-paraglide-js#104]
### Context

Paraglide's current `messages.js` file cannot be properly chunk-split by rollup.

We assumed that the messages can be split / inlined automatically because they are exported separately. However rollup can only remove unused functions from modules, it cannot split functions from the same modules into separate chunks.

Because of this Paraglide currently doesn't properly split messages per-page.

## Proposal

There are two things we could do:

### Option 1

Implement chunk-splitting in Rollup (very large effort) [https://github.com/rollup/rollup/issues/2512](https://github.com/rollup/rollup/issues/2512)

### Option 2

Generate a separate file for each message and re-export all of them from `messages.js`. This drastically increases the number of files in the compiled output but we wouldn't need to do any API changes.

```
|- messages.js.   //barrel file for messages/index/[messageId].js
|- messages/
  |- en.js        //barrel file for messages/en/[messageId].js
  |- en/
     |- messsage_one.js
     |- message_two.js
  |- index/
     |- message_one.js
     |- message_two.js  
```

**Comment by samuelstroschein** [comment]
Is this a problem in turbopack and rolldown? <br><br>If not, we could just wait. Rolldown will eventually replace rollup in vite and turbopack replaces webpack. <br><br>**Re option 2**

* can this be exposed as virtual modules in rollup/vite instead of the real fs to reduce "noise"?

**Comment by LorisSigrist** [comment]
Turbo / Webpack & EsBuild -> Works as expected<br>Rollup / Rolldown -> No Splitting<br><br>Rolldown is a reimplementation of Rollup so it inherits this missing feature. There is no telling how long it will take to add that. Until then all vite-based frameworks won't benefit from the Treeshakeing that should be enabled by paraglide. This fundamentally undermines our Pitch which is why I marked this as urgent. 

> Can this be exposed as virtual modules in rollup/vite

To do this we would need completely separate build outputs for rollup & non-rollup environments. This defeats the purpose of the FS based output IMO. If were to go with Option 2 I would prefer actually emitting the files.

**Comment by samuelstroschein** [comment]
Gut instinct is: fix this in rollup. 

* potentially 1000's of message files will slow down tools (linters etc) and degrade the DX of paraglide
* degrading the DX for all paraglide users because a subset of users (rollup) has issues seems wrong
* fixing this in rollup is beneficial to the entire rollup and web dev community

I would ask the maintainer of rollup (@lukastaegert) if he would fast-track a solution if you work on it, or we could also put a $xK bounty on the rollup issue. <br><br>Putting a substantial bounty on the rollup issue seems easiest.

**Comment by lukastaegert** [comment]
To be honest I am sure I will not be able to divert the necessary resources in the next months independent of the bounty. We recently had a new high-quality contributor in Rollup, maybe I could interest @liuly0322 in the topic and the bounty? I would also be very interested to work on this but I am stretched to my limits. But I would provide any support I can give and feedback about potential approaches.

**Comment by LorisSigrist** [comment]
> @loris.sigrist what do you think about putting a substantial bounty on the issue

Fixing this in Rollup itself would of course be the most elegant solution. However, speed is of the essence as well. While this issue persists Paraglide doesn't live up to it's promise. <br><br>We can fix this quickly with Option 2, any rollup update would need to come reasonably soon in order for it to be worth it for us. <br>If putting a bounty on this get's us that speed then I'm in favor, but if it's going to take months even with the bounty I would prefer going with Option 2.

**Comment by liuly0322** [comment]
Hello, I am also new to rollup, but in my view, there is definitely a huge work for rollup to do to support chunk-splitting. Though esbuild has achived the goal,

1. The internal structure of esbuild and rollup is very different;
2. The bundle speed is also what rollup needs to take into consideration, as esbuild is written in native language, it has a speed advantage, and can do tree-shaking for every different code entry. However for rollup, maybe another approach is needed.

So though personally I think it would be great for rollup to support chunk-splitting, it may not be reasonably soon. I actually think a rollup/vite virtual module plugin is a good idea to balance performance and tree-shaking effect, feel free to ignore me as I don't know how many of your users are using vite :)

**Comment by LorisSigrist** [comment]
`Paraglide-Astro`  and `Paraglide-Sveltekit` both use `Paraglide-Vite` under the hood. We could use that plugin to override imports from `paraglide/messages.js` and `paraglide/messages/[lang].js` with the barrel-file versions. The FS output would remain the same.  <br><br>This would give us the Chunk-Splitting without needing to change the FS output. It would require some duplicate work on the compiler, but as long as it's a temporary fix it would be manageable IMO. <br><br>This is a hack, but it could work. <br>@samuel.stroschein what do you think? Is this what you meant when suggesting we use a rollup plugin?

**Comment by samuelstroschein** [comment]
@loris.sigrist nice. you found a way to do virtual modules in rollup e.g. not writing 1000s of files to disk in [https://github.com/opral/monorepo/pull/2707](https://github.com/opral/monorepo/pull/2707) ?

**Comment by LorisSigrist** [comment]
Correct. FS files stay the same but chunk splitting works
