### ISSUE TITLE
custom NextLink component doesn't forward ref

### ISSUE THREAD

**Issue by NurbekGithub** [opral/inlang-paraglide-js#105]
[`opral/monorepo/inlang/source-code/paraglide/paraglide-next/src/app/Link.tsx`](https://github.com/opral/monorepo/blob/main/inlang/source-code/paraglide/paraglide-next/src/app/Link.tsx)

it creates a visual bug for some ui component libs ([mantine.dev](https://mantine.dev/getting-started/)) and might also cause some other regressions in react

https://github.com/opral/inlang-paraglide-js/assets/24915724/c839db11-fecf-4ed5-a0c9-8eec96992ddf

I tested locally and used React.forwardRef to a NextLink component and it worked as expected. PR incoming

**Comment by LorisSigrist** [comment]
Good catch! Thank you. Excited for the PR!
