### ISSUE TITLE
Doc components not rendering on npm

### ISSUE THREAD

**Issue by NilsJacobsen** [opral/inlang-paraglide-js#111]
I propose to remove those sections:

![image.png](https://uploads.linear.app/4cb6d418-86ee-4425-b5c8-f91266b0ab28/eecc6cf8-ac2e-4113-a7f9-05b0ed5e2eaa/2f8b6301-11e5-493a-b001-7fe55e6067ad?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzRjYjZkNDE4LTg2ZWUtNDQyNS1iNWM4LWY5MTI2NmIwYWIyOC9lZWNjNmNmOC1hYzJlLTQxMTMtYTdmOS0wNWIwZWQ1ZTJlYWEvMmY4YjYzMDEtMTFlNS00OTNhLWIwMDEtN2ZlNTVlNjA2N2FkIiwiaWF0IjoxNzE1MDA2MTg2LCJleHAiOjMzMjg1NTY2MTg2fQ.HRlFw8ycQwHn1WRN54g948E_2GfIHP9cyUsSYcp37v0 "=987x")

**Comment by LorisSigrist** [comment]
What would you replace them with? Just straight markdown lists?

**Comment by NilsJacobsen** [comment]
Yes sounds good.
