### ISSUE TITLE
ignoring paraglide folder in git causes build fail in ci for nextjs

### ISSUE THREAD

**Issue by NurbekGithub** [opral/inlang-paraglide-js#116]
This might not be an issue as I am not sure yet why nextjs plugin generates a `.gitignore` file that ignores everything in paraglide folder since the content of the folder is being used in the app?

Leaving it as it is causes build error in ci env:
`Module not found: Can't resolve '$paraglide/runtime.js'`

removing the `.gitignore` solves the problem, but it is annoying since the plugin generates it again

**Comment by LorisSigrist** [comment]
Does the actual `next build` command fail in CI or are you running some sort of linting, typechecking or formatting first? <br><br>The `next build` command \_should\_ re-run the paraglide compiler so the `paraglide` folder should be regenerated when running it. <br><br>If you want to lint first you will need to first run the paraglide compiler via the CLI before linting

```
paraglide-js compile --project ./project.inlang --outdir ./src/paraglide
```

**Comment by NurbekGithub** [comment]
Sorry, didn't notice your response, will check and get back to you soon @LorisSigrist

**Comment by NurbekGithub** [comment]
The issue is somehow solved itself 😅 . Anyway, I think I will be able to solve it next time with

```js
paraglide-js compile --project ./project.inlang --outdir ./src/paraglide
```

@LorisSigrist thanks!
