### ISSUE TITLE
useRouter does not allow routing to external links

### ISSUE THREAD

**Issue by themataleao** [opral/inlang-paraglide-js#119]
When I am using the useRouter component and route to an external link it throws me a type error:

`Argument of type '"https://google.com"' is not assignable to parameter of type '`/${string}`'`

```typescript
'use client'
import { useRouter } from '@/lib/i18n'

export default function Button(props: {
}) {
  const router = useRouter()
  const { user } = useUser()

  const onClick = async () => {
    router.push("https://google.com")
  }
```

Any other suggestion to route to external URLS?

**Comment by themataleao** [comment]
I am able to trick the typescript compiler with

`router.push(link as `/{string}`)`

but I assume thats not intended :)

**Comment by LorisSigrist** [comment]
Good catch, that is indeed not intended 🙂 I'll fix that. <br><br>The workaround you used should work for the moment. Alternatively you could use the `useRouter` exported from `next/navigation` when you want external links. This won't translate internal links though

**Comment by themataleao** [comment]
You are right I could use the regular one from `next/navigation`. Thanks :)
