### ISSUE TITLE
Paraglide-SvelteKit Parse error when using incompatible svelte versions

### ISSUE THREAD

**Issue by testvinder** [opral/inlang-paraglide-js#133]
When I upgrade @inlang/paraglide-sveltekit from 0.6.23 to any newer version I get this error:

```
[plugin:vite-plugin-svelte] Error while preprocessing /home/user/webApp/src/lib/Components/Lister/Filters.svelte - [@inlang/paraglide-sveltekit] Failed to parse /home/user/webApp/src/lib/Components/Lister/Filters.svelte. 
This may be because you are using a signifficantly newer version of the "svelte" package. 
Try forcing "@inlang/paraglide-sveltekit" to use your version of "svelte" using pnpm overrides
```

I'm using the latest stable version of Sveltekit (2.5.10) and Svelte (4.2.17).

Could it have something to do with this change 0.7.0
    _3e9b863: Use Svelte 5 compiler in the preprocessor for rewriting links_

**Comment by LorisSigrist** [comment]
This error mistakenly gets triggered when there is a Syntax error in your `.svelte` file. <br><br>I updated the behavior so that Paraglide-SvelteKit's preprocessor now logs a warning and No-ops when a syntax error is encountered.

**Comment by testvinder** [comment]
Thank you!
