### ISSUE TITLE
Create ParaglideJS Inlang plugin

### ISSUE THREAD

**Issue by felixhaeberle** [opral/inlang-paraglide-js#140]
@lorissigrist  Do you see the value in bundling the inlang message format plugin & the m function matcher in a dedicated paraglidejs plugin to have a more convenient handling of modules?        
              
> see also [https://discord.com/channels/897438559458430986/1084866749842870333/1247389185862533220](https://discord.com/channels/897438559458430986/1084866749842870333/1247389185862533220) where user has issue identifying how to get Sherlock to work. This happens on a weekly basis, and probably much more silently.

_Originally posted by @felixhaeberle in https://github.com/opral/inlang.com/issues/85#issuecomment-2147127098_

**Comment by LorisSigrist** [comment]
I'm not sure if that's a good idea, since we would be tie-ing the storage format to the API used in code. <br><br>Given that the `init` channels usually add both the m-function matcher & the inlang-message-format: Do we know how users end up with these half-setups?

**Comment by NilsJacobsen** [comment]
Paraglide doesn't need a storage plugin with persistency. So this is only about the matcher for paraglide.

**Comment by felixhaeberle** [comment]
> I'm not sure if that's a good idea, since we would be tie-ing the storage format to the API used in code.

This was discussed yesterday with @samuelstroschein – I also had this misconception. 

With importer/exporter `saveMessage`/`loadMessage` will become `importMessage`/`exportMessage` – with the main change that **not last one wins anymore but multiple importer/exporter plugins are allowed then**, making the import/export of the ParaglideJS plugin the default one + one of many.

> Given that the init channels usually add both the m-function matcher & the inlang-message-format: Do we know how users end up with these half-setups?

🤷🏼 – manual setup? don't know, but happens often.

**Comment by LorisSigrist** [comment]
I see. In that case doesn't it make more sense to wait for persistence to land before doing something like this?

**Comment by samuelstroschein** [comment]
Yes, let's wait for persistence.
