### ISSUE TITLE
split "usage" from "getting started" in docs

### ISSUE THREAD

**Issue by samuelstroschein** [opral/inlang-paraglide-js#141]
### Context

1. I was looking for the getting started but couldn't find it. 
2. Then i found it under "usage" but usage is sooooo much info

<img src="https://uploads.linear.app/4cb6d418-86ee-4425-b5c8-f91266b0ab28/00362eb3-cb46-471a-966a-4f42d429c0fa/f9f78925-7378-44c9-b547-6e65c4e149cb?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzRjYjZkNDE4LTg2ZWUtNDQyNS1iNWM4LWY5MTI2NmIwYWIyOC8wMDM2MmViMy1jYjQ2LTQ3MWEtOTY2YS00ZjQyZDQyOWMwZmEvZjlmNzg5MjUtNzM3OC00NGM5LWI1NDctNmU2NWM0ZTE0OWNiIiwiaWF0IjoxNzE3NTA0NTU0LCJleHAiOjMzMjg4MDY0NTU0fQ.npjI4De8XdCJ-W7-ND83rBfPJZd6JatwI29B9ILjASE " alt="CleanShot 2024-06-04 at 08.34.15@2x.png" width="1036" height="754" />

### Proposal

Split the getting started from usage docs to make "getting started" discoverable in the side bar and don't lead to an "OMG this is all i have to know to get started" reaction

**Comment by NilsJacobsen** [comment]
+1 for seo
