### ISSUE TITLE
feature request: telemetry opt out

### ISSUE THREAD

**Issue by jeiea** [opral/inlang-paraglide-js#142]
It seems telemetry cannot be turned off when using `@inlang/paraglide-next`.

How about adding option about this?

**Comment by LorisSigrist** [comment]
You're right, there currently is no way to deactivate telemetry. We will add an opt-out at some point but don't really see it as urgent right now. 

What's being collected:

* If the `init` command is completed successfully. If not, at which step was it cancelled?
* How many times `compile` is run

**Comment by maiertech** [comment]
Is there now a way to opt out?

Because anyone doing a security audit in a project using Paraglide won't be happy with this error message:

![paraglide](https://github.com/user-attachments/assets/32167921-09cd-493b-8ac6-a02d4f532412)

**Comment by samuelstroschein** [comment]
Hi @maiertech, 

No possibility to opt-out for v1 of paraglide js. Paraglide JS 2.0 has an opt-out possibility but the release of Paraglide JS 2.0 is blocked atm due to a focus shift to lix. Read more here https://opral.substack.com/p/focus-shift-from-inlang-to-lix

**Comment by samuelstroschein** [comment]
implemented in paraglide js 2.0 which is already on the `main` branch but not released yet [https://github.com/opral/monorepo/blob/3d048a73eb36e1c65c58f3e24b72ad214864fdbf/packages/inlang-paraglide-js/src/services/telemetry/capture.test.ts#L4-L25](https://github.com/opral/monorepo/blob/3d048a73eb36e1c65c58f3e24b72ad214864fdbf/packages/inlang-paraglide-js/src/services/telemetry/capture.test.ts#L4-L25)
