### ISSUE TITLE
SvelteKit client-side paraglide:lang cookie won't update

### ISSUE THREAD

**Issue by twoends** [opral/inlang-paraglide-js#148]
In changelog 0.9.3 I see:

`def2d4e: fix: Also update the paraglide:lang cookie on the client to allow for better language negotiation`

Unfortunately client-side cookie won't update since it's created as HttpOnly. If I manually set HttpOnly to false, clicking `<a href={i18n.route($page.url.pathname)} hreflang={lang}>` will update the cookie correctly.

Despite this, I'm not sure setting HttpOnly to false is an acceptable solution.

**Comment by twoends** [comment]
It shouldn't be created as HttpOnly by default. Don't know if some browser policies are getting updated. Btw, tested on Edge, Chrome, Firefox and Safari. Only Safari creates it as non-HttpOnly

**Comment by LorisSigrist** [comment]
Very weird, I'll make sure to test thurouhly test the changes in all browser
