### ISSUE TITLE
show good and bad example for server side usage in docs

### ISSUE THREAD

**Issue by samuelstroschein** [opral/inlang-paraglide-js#152]
## Context

[https://www.reddit.com/r/sveltejs/comments/1dbx0ps/comment/l7v18d2/?utm_source=share&utm_medium= web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button](https://www.reddit.com/r/sveltejs/comments/1dbx0ps/comment/l7v18d2/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button)

> That document illustrates a solution, but it could use more clarification on what problem it solves. Specifically, an example showing the "bad approach" would go a long way here to help the reader determine whether they themselves are suffering from this problem.

## Proposal

Show a good and bad example like [https://eslint.org/docs/latest/rules/no-debugger#rule-details](https://eslint.org/docs/latest/rules/no-debugger#rule-details) for on [https://inlang.com/m/dxnzrydw/paraglide-sveltekit-i18n/serverside-usage](https://inlang.com/m/dxnzrydw/paraglide-sveltekit-i18n/serverside-usage)

**Comment by LorisSigrist** [comment]
@nils.jacobsen Just a code example, there already is a PR, although I'm not yet happy with the wording
