### ISSUE TITLE
Gracefully handle Project Errors

### ISSUE THREAD

**Issue by LorisSigrist** [opral/inlang-paraglide-js#156]
### Context

Currently paraglide crashes on any Project errors. 

### Proposal

Only crash if the plugins responsible for loading messages fail to load.

**Comment by samuelstroschein** [comment]
this does not seem to be a paraglide issue. the inlang sdk should have a `project.errors` or `project.exceptions` property that contains non-critical errors (like a module not loading). 

paraglide could then decide to throw if a project has exceptions, or continue running

**Comment by LorisSigrist** [comment]
Depending on the app different things may count as "exceptions" vs "errors". <br><br>In Paraglide only a Plugin not loading would be fatal, whereas in Sherlock a function-matcher might count as "fatal". Future apps will have completely different requirements. <br><br>Giving apps a clear, well typed picture of what went wrong & having them react appropriately would be more flexible. This avoids turning the "exception" vs "error" discussion into another SDK topic. <br><br>Do you agree?

**Comment by samuelstroschein** [comment]
Yes, expose everything under `project.errors`() and let apps decide for themselves if they throw or not. 

Clarification: I did not mean to separate errors and exceptions. I just forgot that we already exposed `project.errors` :)
