### ISSUE TITLE
Circular dependecy in svelte@5.0.0-next.143 in CI

### ISSUE THREAD

**Issue by jldec** [opral/inlang-paraglide-js#157]
### Context

I don't know if this is serious, but many of the CI runs in GitHub are showing messages like this. I went back a few weeks, and it appears to have been happening for while.

```
Circular dependency: ../../../../node_modules/.pnpm/svelte@5.0.0-next.143/node_modules/svelte/src/internal/client/runtime.js -> ../../../../node_modules/.pnpm/svelte@5.0.0-next.143/node_modules/svelte/src/internal/client/proxy.js -> ../../../../node_modules/.pnpm/svelte@5.0.0-next.143/node_modules/svelte/src/internal/client/dev/ownership.js -> ../../../../node_modules/.pnpm/svelte@5.0.0-next.143/node_modules/svelte/src/internal/client/runtime.js
```

To see these, open an instance of the `Continuous Integration` workflow like [this one](https://github.com/opral/monorepo/actions/runs/9568178493/job/26377736009) and use the built-in search to look for "Circular"

![Screenshot 2024-06-18 at 16 58 41](https://github.com/opral/inlang-paraglide-js/assets/849592/6b5e7ffd-90b1-44bb-8631-3be4536e613f)

### Proposal

decide if worth investigating or close the issue if not 😃

**Comment by LorisSigrist** [comment]
This seems to be caused by how the integration tests bundle svelte. Not a problem, but I'll try to suppress the error

**Comment by jldec** [comment]
Thanks @LorisSigrist
