### ISSUE TITLE
Typescript `isolatedDeclarations` and `allowJS` with paraglide.

### ISSUE THREAD

**Issue by minht11** [opral/inlang-paraglide-js#160]
Typescript 5.5 add support for [isolated declarations](https://devblogs.microsoft.com/typescript/announcing-typescript-5-5/#using-isolateddeclarations). This is to speedup tooling and so on. Unfortunately `"isolatedDeclarations": true` does not work with `"allowJs": true` which is required to use paraglide.

Isolated declarations promise huge speed up for typescript and other related tooling, so I hope there is way to use it while using paraglide. Possibly generating declaration files along side compiled messages?

**Comment by LorisSigrist** [comment]
IMO This is a typescript issue: [microsoft/TypeScript#58262](https://github.com/microsoft/TypeScript/issues/58262)

Paraglide's output is fully typed using JSDoc. TypeScript has enough information to generate a declaration file in parallel the way it does for `isolatedDeclarations`,  they just haven't implemented that yet. They likely will at some point.

I am hesitant to change Paraglide's output to accommodate a likely temporary restriction from a brand-new TS version.

**Comment by samuelstroschein** [comment]
I also pushback. The overhead in paraglide's compiler to emit ts files or declaration files only is huge (i tried). 

typescript should fix this on their end.
