### ISSUE TITLE
frontmatter on npm

### ISSUE THREAD

**Issue by NilsJacobsen** [opral/inlang-paraglide-js#162]
<img src="https://uploads.linear.app/4cb6d418-86ee-4425-b5c8-f91266b0ab28/b73103b7-da85-4678-8ae5-18f4c1d91dec/6915ffe7-a3c8-4188-8614-91c2648f45e6?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzRjYjZkNDE4LTg2ZWUtNDQyNS1iNWM4LWY5MTI2NmIwYWIyOC9iNzMxMDNiNy1kYTg1LTQ2NzgtOGFlNS0xOGY0YzFkOTFkZWMvNjkxNWZmZTctYTNjOC00MTg4LTg2MTQtOTFjMjY0OGY0NWU2IiwiaWF0IjoxNzE5MjEyMDE4LCJleHAiOjMzMjg5NzcyMDE4fQ.IBoAV_yqnp42A3-cy0Tyq8lRflALWAwrvVnF03hNui8 " alt="image.png" width="1049" height="583" />

At some point, we should maybe have an extra page for npm. Or we remove frontmatter.

**Comment by LorisSigrist** [comment]
Removing frontmatter from the README seems the most appropriate
