### ISSUE TITLE
sveltekit cloudflare adapter can't work with paraglide

### ISSUE THREAD

**Issue by nosovk** [opral/inlang-paraglide-js#163]
There is an "node:async_hooks" used inside sveltekit adapter.
https://github.com/opral/monorepo/blob/606c8d8f18302a35a7356206a9b1c480e9c8191b/inlang/source-code/paraglide/paraglide-sveltekit/src/runtime/hooks/handle.server.ts#L10

but unfortunately it's not supported in cloudflare pages environment.

**Comment by nosovk** [comment]
"@inlang/paraglide-sveltekit": "^0.6.23"
works, rolled back to it

**Comment by nosovk** [comment]
https://nodejs.org/api/async_hooks.html
actually it's recommended not to use it all

**Comment by nosovk** [comment]
nodejs_compat is not recommended, it affects performance of cloudflare workers, if possible it's better to activate it. Actually enabling it is a blocker to upgrade to current paraglide version.

**Comment by LorisSigrist** [comment]
I might be able to replace `AsyncLocalStorage` with [unctx](https://unjs.io/packages/unctx) and their build-time vite-plugin. <br><br>I'll try that & get back to you

**Comment by samuelstroschein** [comment]
More users are running into this problem. See discord https://discord.com/channels/897438559458430986/1083724234142011392/1256638811769667695

**Comment by nosovk** [comment]
Solid does not requre that flag according to documentation https://developers.cloudflare.com/pages/framework-guides/deploy-a-solid-site/

In edge adapters there is no parallel execution of multiple requests in one env, that's why there is no benefit from from AsyncLocalStorage in CloudFlare Pages adapter, Vercel adapter etc. 

It' could be helpful if you use node adapted, but actually I never saw it working like that in production (due of performance issues, which are solved by edge funktions architecture).

I hope that in future releases there will be an option to opt out of that.

**Comment by nosovk** [comment]
https://github.com/opral/monorepo/blob/main/.changeset/fast-stingrays-leave.md

**Comment by misaelvillaverde** [comment]
I have the same issue with astro + cloudflares, using `nodejs_compat` nor `nodejs_als` works though. I will just try to rollback.
```
[plugin vite:resolve] Cannot bundle Node.js built-in "node:async_hooks" imported from "node_modules/@inlang/paraglide-astro/dist/middleware.js"
```

**Comment by nosovk** [comment]
@misaelvillaverde we just pinned old version, but it seems that there is a option (but not documented) to disable that experimental things now.
