### ISSUE TITLE
Revert "`paraglide-js init` prompt for user tech stack"

### ISSUE THREAD

**Issue by LorisSigrist** [opral/inlang-paraglide-js#166]
### Context

[PARJS-33](https://linear.app/opral/issue/PARJS-33/[improvement]-paraglide-init-prompts-the-user-for-the-tech-stack-js)

A while back we started prompting users about their tech-stack during `paraglide-js init` to guide them to the docs relevant to their framework. In practice this hasn't been helpful.

* Both `paraglide-sveltekit` and `paraglide-next` have their own `init` CLIs 
* The Framework specific guides are already prominently linked in the docs
* The Prompt is unexpected & does not do anything immediately relevant. It feels like bloat during the installation. 

CC @samuel.stroschein 

### Proposal

Remove this prompt & rely on the docs to guide people to the relevant documentation for their Framework.

**Comment by samuelstroschein** [comment]
yep go for it
