### ISSUE TITLE
add explainer on how to deploy on cloudflare

### ISSUE THREAD

**Issue by samuelstroschein** [opral/inlang-paraglide-js#172]
"Maybe it would be good to add a small explainer to the website as it's not 100% intuitive and quite some people are using cloudflare to deploy svelte"

**Comment by Skymax00** [comment]
You can fix it directly from the Cloudflare Pages settings:

![image](https://github.com/user-attachments/assets/c709c30e-68e8-44cc-9c24-78e984c87812)
