### ISSUE TITLE
Always using fallback langauge when app is running in capacitor

### ISSUE THREAD

**Issue by SaintPepsi** [opral/inlang-paraglide-js#190]
When I build my `svelte-kit` application for `capacitor` there's a 2 issues that come up:

1. Paraglide is unable to detect the device language and so always uses the default language.
2. Language cookie is set to default language, but not updated to other languages (I presume this is due to cookie issues in webviews)

For the second one it's probably possible to store the language tag in local storage instead to see if that works, i'll try this when I have a chance next.

**Comment by SaintPepsi** [comment]
I tried using `setLanguageTag` in the client hooks, but something was not quite right as it would load a blank page sometimes or wouldn't correctly redirect.

Perhaps there's another way to do it?

**Comment by SaintPepsi** [comment]
I was able to figure out how to get the language working with capacitor and cloudflare workers.

it's not pretty but it works and I have no idea why.

I first check if a user saved language exists in local storage. (or device language)
if one of those does:
use `setLanguageTag` and then call `i18n.resolveRoute` with the current `pathname` and the desired language.

if i use `redirect` i get a double lang url `/[lang]/[lang]` 

And this is only required for cloudflare workers and capactior (adapter static) builds

```ts
export const load: LayoutLoad = async ({ depends, url, route }) => {
	if (!['capacitor', 'cloudflare-workers'].includes(import.meta.env.VITE_ADAPTER)) {
		return;
	}

	depends('paraglide:lang');

	const userLanguage = await getUserPreference('LANGUAGE');

	if (isAvailableLanguageTag(userLanguage)) {
		setLanguageTag(userLanguage);
		i18n.resolveRoute(url.pathname, userLanguage);
		return;
	}

	const { value: deviceLanguageCode } = await Device.getLanguageCode();

	if (isAvailableLanguageTag(deviceLanguageCode)) {
		setLanguageTag(deviceLanguageCode);
		i18n.resolveRoute(url.pathname, deviceLanguageCode);
	}
};
```

No clue why calling `i18n.resolveRoute` allows the application to actually perform the correct routing.

**Comment by samuelstroschein** [comment]
So problem solved?

**Comment by SaintPepsi** [comment]
> So problem solved? 

You could say that haha but I don't understand why this behaviour is working. Could you elaborate on the internals as to why this approach might work?

**Comment by samuelstroschein** [comment]
Atm I can't. Haven't digged into the i18n routing implementation yet
