### ISSUE TITLE
fetch() ignores exclude /api

### ISSUE THREAD

**Issue by elron** [opral/inlang-paraglide-js#191]
when I run this in my `+page.svelte`

```const res = await fetch(`/api/reveal-pro/${confettiRef.id}`, { method: 'POST' });```

it fetches from `/he/api/...`  (with the language tag: `/he` or `/en`, when it should be fetch without language tag `localhost:1234/api`

<img width="870" alt="image" src="https://github.com/user-attachments/assets/7ada84a4-9ac5-42a2-9737-d6993658f8a9">

even that I have `/api` in the exclude:

```
export const i18n = createI18n(runtime, {
  prefixDefaultLanguage: 'always',
  exclude: [
    '/api',
    '/test',
    '/a',
    '/sitemap.xml',
    '/example'
  ],
  textDirection: {
		en: "ltr",
		he: "rtl",
	},
});
```

How do I bypass that problem?

**Comment by samuelstroschein** [comment]
Does excluding the `/api` route fix the problem? see https://inlang.com/m/dxnzrydw/paraglide-sveltekit-i18n/advanced-usage#excluding-certain-routes

**Comment by LorisSigrist** [comment]
This is incredibly weird, `fetch` isn't supposed to be rewritten *at all*. `exclude` shouldn't be needed. I'll look into this

Are you using the normal `fetch` function or the one passed as an argument in `+page.server.ts#load`?

**Comment by elron** [comment]
I think I use the normal one, not svelte one.
Because this runs on the browser.

**Comment by elron** [comment]
> Does excluding the `/api` route fix the problem? see https://inlang.com/m/dxnzrydw/paraglide-sveltekit-i18n/advanced-usage#excluding-certain-routes

I can't disable it, otherwise I will literally have two API endpoints for two different languages. Exclude is needed

**Comment by elron** [comment]
I didn't notice before but I thought this is important to mention that this fetch function runs twice.
Maybe this will beneficial:
https://www.loom.com/share/1087f09d69544119a379c9832ceb8e94

**Comment by elron** [comment]
That fixed it!

Maybe add to the documentation?

**Comment by LorisSigrist** [comment]
I will!

**Comment by elron** [comment]
Thanks for the support

**Comment by add-n2x** [comment]
Had the same  problem and that fixed it:

```js
export const i18n = createI18n(runtime, {
  exclude: ["/api", /^\/api\/.*/]
})
```

That took me quite some time to find out. So yes, please, add it to the docs.

**Comment by samuelstroschein** [comment]
@add-nx2 can you open a PR to update the docs? Will merge it promptly

**Comment by hazre** [comment]
I've also ran into this issue on my /api routes as well, this definitely needs to be documented somewhere.
