### ISSUE TITLE
next 14 app router hydration mismatch

### ISSUE THREAD

**Issue by samuelstroschein** [opral/inlang-paraglide-js#195]
From discord

Hi guys, nice to meet you all. I need some help regarding paraglide next.js. **Context:** So I have a project with next 14 (app router) and I'm using paraglide. I've followed the tutorial on [https://inlang.com/m/osslbuzt/paraglide-next-i18n/get-started](https://inlang.com/m/osslbuzt/paraglide-next-i18n/get-started) and the translation is working properly. My source language is pt-br and I have the following supported languages: "pt-br", "en-US", "es-ES" **Problem:** when I load my localhost:3000, the page is in pt-br as expected, but when I navigate to localhost:3000/en-US or localhost:3000/es-ES I receive hydration errors (images). Also, I'm not using any browser extensions. I've searched a lot but couldn't figure out how to solve this =/ I'll be very glad if someone could help. Thanks

**Repo:** [https://github.com/luizlevindiniz/lp-fixes-inlang](https://github.com/luizlevindiniz/lp-fixes-inlang) (how to reproduce: yarn install and yarn run dev -> open localhost:3000 -> open browser console -> assure no errors are showing -> navigate to localhost:3000/en-US -> check the console again) **(edited)**

<img src="https://uploads.linear.app/4cb6d418-86ee-4425-b5c8-f91266b0ab28/00252182-58ed-4536-baf2-cc26b615cee0/3a054212-402a-485a-95dd-d71f9c70cc9e?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzRjYjZkNDE4LTg2ZWUtNDQyNS1iNWM4LWY5MTI2NmIwYWIyOC8wMDI1MjE4Mi01OGVkLTQ1MzYtYmFmMi1jYzI2YjYxNWNlZTAvM2EwNTQyMTItNDAyYS00ODVhLTk1ZGQtZDcxZjljNzBjYzllIiwiaWF0IjoxNzI0NDQ5NDgzLCJleHAiOjMzMjk1MDA5NDgzfQ.Gn-OEcT6Uwd3n4-fPKRLzwflVxfzS1OuA8sNW5hhLFU " alt="image.png" width="571" height="91" />

![image.png](https://uploads.linear.app/4cb6d418-86ee-4425-b5c8-f91266b0ab28/3be148ca-d9a3-46ae-8620-23fa0703faf2/60f07003-1f5b-4aa3-85e7-7287d62b4bb6?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzRjYjZkNDE4LTg2ZWUtNDQyNS1iNWM4LWY5MTI2NmIwYWIyOC8zYmUxNDhjYS1kOWEzLTQ2YWUtODYyMC0yM2ZhMDcwM2ZhZjIvNjBmMDcwMDMtMWY1Yi00YWEzLTg1ZTctNzI4N2Q2MmI0YmI2IiwiaWF0IjoxNzI0NDQ5NDc0LCJleHAiOjMzMjk1MDA5NDc0fQ.fLC8IzxxlSZCzVv9p73TZGwU7z1whxYSYEuwtYnZPQA "=575x")

**Comment by luizlevindiniz** [comment]
Hi all, I'm the one who sent this issue. If someone could aid me I would be very very grateful.

**Comment by samuelstroschein** [comment]
Hi @luizlevindiniz, I am taking over paraglide js from loris this week.

Do you still face this issue?

**Comment by luizlevindiniz** [comment]
Hi Samuel, how are you?
No, we manage to solve this issue. The problem was that we wore rendering a component via mapping. After change the map to a hard-coded constants the error vanished.

**Comment by feldrok** [comment]
Hi, i'm encountering this issue too, mapping causes hydration problems... how would you solve this if I actually need to map the values? Hard-coded sounds like a biiggg pain for this.

**Comment by samuelstroschein** [comment]
@feldrok can you show code on what you mean with mapping?
