### ISSUE TITLE
expose compiler as library

### ISSUE THREAD

**Issue by samuelstroschein** [opral/inlang-paraglide-js#206]
## Context

It's useful to have the compiler exported as library to enable various use cases. 

- extending the compiler to interpolate components without first class support [discord](https://discord.com/channels/897438559458430986/1291493817190715443/1291735620141580391)
- don't emit prettierignore, gitignore files https://github.com/opral/inlang-paraglide-js/issues/189#issuecomment-2381607612
- calling compile on server startup (instead of the cli, or build step) 

## Proposal 

Expose the compiler to give three options of using Paraglide JS: 

1. a cli command
2. a bundler plugin 
3. as library (calling compile on the fly)

**Comment by tomas-correia** [comment]
Looking forward to this.

It's helpful to be able to trigger compilation in watch mode from my code when I'm already using a watch mode to watch for changes in my code and not using a bundler.

For example, I'm using TSX in watch mode to run TypeScript and watch for changes. It's not possible to trigger the Paraglide compile watch command and TSX watch mode at the same time without some conccurrent scripts package or 2 terminal windows.
