### ISSUE TITLE
Allow deleting messages from cli/sherlock

### ISSUE THREAD

**Issue by Forsect** [opral/inlang-paraglide-js#220]
[Context](https://discord.com/channels/897438559458430986/1283048712448376873) (Discord)

How about adding the feature to remove messages from all language files quickly? I made a big refactor in my code and I have hundreds of unused messages shared by 12 languages. Removing them from all files by hand will be a nightmare. Would love to get some cli/sherlock command where I just pass the name of the translation, and it gets removed from everywhere ❤️

**Comment by samuelstroschein** [comment]
I opened related issues in the apps to close this one. CLI i would leave out for now as I don't want more maintenance effort on the CLI and think once Sherlock and Fink can delete the feature in the CLI is merely nice to have. 

[https://github.com/opral/inlang-sherlock/issues/97](https://github.com/opral/inlang-sherlock/issues/97)

<br>[https://github.com/opral/inlang-fink/issues/51](https://github.com/opral/inlang-fink/issues/51)
