### ISSUE TITLE
direction set to ltr in arabic in firefox base browser "Zen"

### ISSUE THREAD

**Issue by IslamZaoui** [opral/inlang-paraglide-js#231]
I have an issue with my sveltekit portfolio when I open it in Zen browser, the language direction is set to ltr upon page load.

https://github.com/user-attachments/assets/33a673dc-4b65-45bd-bf03-6dbbf134c9d6

is there any fix for that?

**Comment by EcksDy** [comment]
This is what I've done inside `i18n.ts` file:

```ts
import { createI18n } from '@inlang/paraglide-sveltekit';
import * as runtime from '$lib/paraglide/runtime.js';

export const i18n = createI18n(runtime, {
  prefixDefaultLanguage: 'always',
  textDirection: {
    en: 'ltr',
    // ...
  },
});
```

You need to set it explicitly, since paraglide has issues with detecting lang direction automatically in certain conditions.

**Comment by samuelstroschein** [comment]
@EcksDy thanks for chipping in. @IslamZaoui does @EcksDy's suggestion fix the problem?

**Comment by IslamZaoui** [comment]
@samuelstroschein Yes @EcksDy's suggestion fixed the problem
