### ISSUE TITLE
Repo URL missing from npm

### ISSUE THREAD

**Issue by benmccann** [opral/inlang-paraglide-js#240]
https://www.npmjs.com/package/@lix-js/client doesn't have a link to the code

**Comment by manuel3108** [comment]
Indeeed, but it's living here: https://github.com/opral/monorepo/tree/main/lix/packages/client

**Comment by samuelstroschein** [comment]
Yep but the package lix-js/client is deprecated. 

We are in the middle of [rebuilding lix from scratch on SQLite](https://opral.substack.com/p/opral-company-update-september-2024) in the `lix-integration` branch [https://github.com/opral/monorepo/tree/lix-integration](https://github.com/opral/monorepo/tree/lix-integration). the new packge is `@lix-js/sdk`.

I will close this issue given that the `client` package will be removed with the merger of `lix-integration`.

Thanks for opening the issue!
