### ISSUE TITLE
`@inlang/paraglide-sveltekit 0.11.1` breaks language change detection

### ISSUE THREAD

**Issue by TimFoerster** [opral/inlang-paraglide-js#243]
After updating to version 0.11.1, locale switches are not detected anymore and does not trigger loading of remote data (`depends`).

**Comment by samuelstroschein** [comment]
I am wondering if the cookie name change caused this, or updating the dependencies. See the [changelog](https://github.com/opral/monorepo/blob/main/inlang/source-code/paraglide/paraglide-sveltekit/CHANGELOG.md#0111). 

I don't have the capacity atm to look into the bug. Help and a PR is highly appreciated! (PRs will be reviewed and merged)

**Comment by oskarrough** [comment]
Just noticed if you add `depends('paraglide_lang') inside a server load function, it does re-run.

````
export async function load({depends}) {
	depends('paraglide_lang')
	const page = await getPage('home')
	return {page}
}
```

I believe it used to be `paraglide:lang`, so maybe that needs to be updated somewhere. Looking...

**Comment by samuelstroschein** [comment]
@oskarrough here is the PR https://github.com/opral/monorepo/pull/3155. I'll fix the issue and publish a patch!

**Comment by samuelstroschein** [comment]
Fix published as `0.11.3`

**Comment by TimFoerster** [comment]
Can't update to `0.11.3` due to not published `@inlang/paraglide-vite@1.2.76` version.
```
"@inlang/paraglide-js": "1.11.3",
"@inlang/paraglide-sveltekit": "0.11.3",
```
```
npm error code ETARGET
npm error notarget No matching version found for @inlang/paraglide-vite@1.2.76.
npm error notarget In most cases you or one of your dependencies are requesting
npm error notarget a package version that doesn't exist.
```

**Comment by samuelstroschein** [comment]
Thanks for the ping. Our CI on main doesn't auto publish. So annoying

**Comment by samuelstroschein** [comment]
Published! Lmk if it doesn't work
