### ISSUE TITLE
Using language-specific files and routes

### ISSUE THREAD

**Issue by fraboniface** [opral/inlang-paraglide-js#249]
When writing longer texts, like privacy policy, terms, or blog posts, it's often easier to write it in markdown, translate the entire file and convert each to html / svelte separately, as compared to creating keys with huge contents in json files, which are a pain to edit.

I've done so on my website for terms and privacy, with en routes `/privacy` and `/terms `and the corresponding fr routes `/protection-des-donnees` and `/cgu`.

It works fine superficially with paraglide, as the en routes only appear on en pages and likewise for fr. But still, paraglide doesn't "know" that each of those routes is associated to a single language, which makes e.g. a language switcher hard to implement. I've tried setting localized routes but it does the opposite of what I want: it always routes to the default-language page even from another language

Is there a way to make it work?

I still need standard localization for less text-rich pages, for which paraglide is awesome.

**Comment by fraboniface** [comment]
Solved it by putting the language-specific html files in their own component (`terms_en.html` -> `TermsEn.svelte` and same for fr). I could then merge the language-specific routes/folders and those components conditionnaly depending on `languageTag`.

```svelte
<script>
	import { languageTag } from '$lib/paraglide/runtime';
	import PrivacyEn from '$lib/legal/PrivacyEn.svelte';
	import PrivacyFr from '$lib/legal/PrivacyFr.svelte';
</script>

<div class="max-w-3xl text-justify">
	{#if languageTag() == 'fr'}
		<PrivacyFr />
	{:else}
		<PrivacyEn />
	{/if}
</div>
```

Finally, I just needed to use localized routes as demonstrated in the docs to make it work.

**Comment by fraboniface** [comment]
Solved it by putting the language-specific html files in their own component (`terms_en.html` -> `TermsEn.svelte` and same for fr). I could then merge the language-specific routes/folders and those components conditionnaly depending on `languageTag`.

```svelte
<script>
	import { languageTag } from '$lib/paraglide/runtime';
	import PrivacyEn from '$lib/legal/PrivacyEn.svelte';
	import PrivacyFr from '$lib/legal/PrivacyFr.svelte';
</script>

<div class="max-w-3xl text-justify">
	{#if languageTag() == 'fr'}
		<PrivacyFr />
	{:else}
		<PrivacyEn />
	{/if}
</div>
```

Finally, I just needed to use localized routes as demonstrated in the docs to make it work.

**Comment by samuelstroschein** [comment]
Thanks for showing how you solved the issue @fraboniface! :) 

Generally, Paraglide JS is good for UI copy e.g. buttons, short-form stuff, that needs to address the user with gendering, pluralization & Co. For long form copy like a blog post, the inlang ecosystem will come up with dedicated solutions in the future
