### ISSUE TITLE
Variable translation in svelte inlang

### ISSUE THREAD

**Issue by oluijks** [opral/inlang-paraglide-js#250]
I have 3 message files, 'en', 'nl', 'uk'
With a language translation: 
"lang": "English" / "lang": "Nederlands" / "lang": "Уранський"

In my language switcher component:

```ts
{#each availableLanguageTags as language}
  <DropdownMenu.Item onclick={() => switchToLanguage(language)}>
    {m.lang({}, { languageTag: language })}
  </DropdownMenu.Item>
{/each}
```

How would I go about getting the translated language for "lang"?

**Comment by samuelstroschein** [comment]
is `m.lang()` not returning the message in the language provided with `{ languageTag: language }` ?
