### ISSUE TITLE
Component parsing fail in SvelteKit with Svelte 5

### ISSUE THREAD

**Issue by Arkanii** [opral/inlang-paraglide-js#252]
![image](https://github.com/user-attachments/assets/7e09ab97-2a98-47d0-82d7-3a46eda43088)

Hello !

I have a problem when I want to Paraglide transform the <a> links to translated ones...
Every component where there is a link, it fails. Even in node_module folder. (more examples below)
And for this example, if I comment all the components, it works.

But if I try SvelteKit with Paraglide included demo, everything works.

Both projects have the same config and same version.

I know that the error happen here : https://github.com/opral/monorepo/blob/main/inlang/source-code/paraglide/paraglide-sveltekit/src/vite/preprocessor/index.ts#L63
Maybe it's a Svelte related bug and not Paraglide one ?
And it seems the TS parsing if often the cause of the error. But sometimes it's component import.

Thanks a lot ! 🙏🏻 
 
![image](https://github.com/user-attachments/assets/5d78c722-dbc2-4365-9fe5-ac6bdb0d02b9)
![image](https://github.com/user-attachments/assets/916aa364-1b3b-40d8-adae-bdb326b94b0c)

vite.config.ts
```ts
import { paraglide } from '@inlang/paraglide-sveltekit/vite';
import { defineConfig } from 'vitest/config';
import basicSsl from '@vitejs/plugin-basic-ssl';
import { sveltekit } from '@sveltejs/kit/vite';

export default defineConfig({
	plugins: [
		sveltekit(),
		basicSsl(),
		paraglide({
			project: './project.inlang',
			outdir: './src/lib/paraglide'
		})
	],
	test: {
		include: ['src/**/*.{test,spec}.{js,ts}']
	},
	server: {
		host: true,
		strictPort: true
	},
	ssr: {
		noExternal: ['@zenstackhq/tanstack-query']
	}
});
```

**Comment by samuelstroschein** [comment]
The svelte dependency has not been updated to svelte 5. I assume that the svelte compiler emits an old component that leads to problems with svelte 5. <br><br>Can you try updating the svelte dependency in paraglide-sveltekit to v5 and see if the error disappears? <br><br>If yes, testing if sveltekit versions with svelte <5 still work and then opening a PR is highly appreciated.

**Comment by ambigos1** [comment]
Paraglide-js is not supporting svelte 5.
I updated all the packages for the latest version and I am getting a build error.
I reverted my update to svelte 5 till it will be fixed (Hopefully soon) so I am not able to add the exact error I got.

**Comment by Arkanii** [comment]
> The svelte dependency has not been updated to svelte 5. I assume that the svelte compiler emits an old component that leads to problems with svelte 5.

https://github.com/opral/monorepo/tree/main/inlang/source-code/paraglide/paraglide-sveltekit#L33

I see that the version used is 5.

**Comment by Arkanii** [comment]
For a stange reason I've deleted my `node_modules` folder and run `bun install` and it works...

but thanks for your time, I'll close this issue.
