### ISSUE TITLE
LanguageTag gets lost when using goto()

### ISSUE THREAD

**Issue by jis3r** [opral/inlang-paraglide-js#254]
In some scenarios, a link is not sufficient (e.g. when data has to be manipulated before a user gets sent to the next site). I use Svelte's goto()-function in those scenarios, but of course, the LanguageTag is being ignored in those cases. I couldn't find a solution for this in the current docs. It would be awesome, if the LanguageTags could be integrated with that!

(Of course let me know if I am missing something :D )

**Comment by jis3r** [comment]
I built this workaround utility, but of course an integrated solution would still be awesome ;)

```JS
import { languageTag } from '$lib/paraglide/runtime.js';
import { goto as moveto } from '$app/navigation';

function goto(path) {
	let target = '/' + languageTag() + path;
	moveto(target);
}
```

**Comment by ircg-dev** [comment]
> I built this workaround utility, but of course an integrated solution would still be awesome ;)
> 
> ```js
> import { languageTag } from '$lib/paraglide/runtime.js';
> import { goto as moveto } from '$app/navigation';
> 
> function goto(path) {
> 	if (languageTag() === 'de') {
> 		moveto(path);
> 	} else {
> 		let target = '/' + languageTag() + path;
> 		moveto(target);
> 	}
> }
> ```

I thing you can use the goto as  `goto(i18n.resolveRoute("/about"))` and avoid to use that workaround.

You can read about it [here](https://inlang.com/m/dxnzrydw/paraglide-sveltekit-i18n/localised-routing#programmatic-navigation-with-translated-paths)

**Comment by samuelstroschein** [comment]
Already exists via the `i18n.resolveRoute` API [https://inlang.com/m/dxnzrydw/paraglide-sveltekit-i18n/localised-routing#programmatic-navigation-with-translated-paths](https://inlang.com/m/dxnzrydw/paraglide-sveltekit-i18n/localised-routing#programmatic-navigation-with-translated-paths)
