### ISSUE TITLE
Similar to the use:enhance error, wretch encountered an error. http://localhost:5175/en/api/ -> 405. 

### ISSUE THREAD

**Issue by Tran-Duc-Duy** [opral/inlang-paraglide-js#258]
const onLogout = async () => {
		await wretch('/api/auth/logout').post().json();
	};
	
I'm trying to call the logout api of the sveltekit server, but the url has an unwanted prefix "/en" added. And it's rejected by the server.
![image](https://github.com/user-attachments/assets/c351df2f-23ae-4890-a91b-3fdea300098a)
![image](https://github.com/user-attachments/assets/cdd7d77e-1a1c-4470-90c8-97153c028734)
I call the POST method, where does the GET method come from? I followed: https://inlang.com/m/dxnzrydw/paraglide-sveltekit-i18n/getting-started

**Comment by samuelstroschein** [comment]
did you try to exclude the route? [https://inlang.com/m/dxnzrydw/paraglide-sveltekit-i18n/advanced-usage#excluding-certain-routes](https://inlang.com/m/dxnzrydw/paraglide-sveltekit-i18n/advanced-usage#excluding-certain-routes)

**Comment by samuelstroschein** [comment]
closing because stale. re-open if excluding the route doesn't work.
