### ISSUE TITLE
Use virtual files instead of outputting to `src` directory

### ISSUE THREAD

**Issue by benmccann** [opral/inlang-paraglide-js#264]
When you setup Paraglide with SvelteKit it does `outdir: './src/lib/paraglide'`. It's fairly weird to output source code to the `src` directory and to have to then ignore it from git, eslint, prettier, etc.

The typical solution to this would be a Vite plugin outputting a virtual file: https://vite.dev/guide/api-plugin#virtual-modules-convention

If you want something more bundler agnostic you can use unplugin: https://github.com/unjs/unplugin

**Comment by manuel3108** [comment]
Just found this by accident, this is the original issue where this came up: https://github.com/sveltejs/cli/issues/308

**Comment by samuelstroschein** [comment]
@manuel3108, thanks for the context. Are you open for a PR? I'll quickly review and merge it. 

I'd suggest to add a new config property `useVirtualModules: boolean (default false)` in the vite plugin. If set to `true`, the files are not written to disk. 

Todos: 

- [ ] write to virtual modules if `useVirtualModules` is here https://github.com/opral/monorepo/blob/39c013d01e6134fc5ad07818949e260fc815abba/inlang/source-code/paraglide/paraglide-unplugin/src/index.ts#L73

**Comment by manuel3108** [comment]
Had a brief look at this right now, but this doesn't look to be as trivial as expected. Had a look at this [vite-plugin](https://github.com/patak-dev/vite-plugin-virtual) that we would probably need to use. This would also require dynamically emitting `.d.ts`.

I'm not going to have enough time to have a deeper look at this over the next few weeks, might revisit later.
