### ISSUE TITLE
paraglide-next does not await headers

### ISSUE THREAD

**Issue by amazfs** [opral/inlang-paraglide-js#267]
Paraglide does not switch language based on browser language. This error is raised:

Error: Route "/" used `headers().get('x-language-tag')`. `headers()` should be awaited before using its value. Learn more: https://nextjs.org/docs/messages/sync-dynamic-apis
    at unsafeLanguageTag (paraglide\runtime.js:77:20)
    at languageTag (webpack-internal:\(rsc)\app\app\layout.js:20:15)
    at Object.apply (webpack-internal:\(rsc)\app\sentry-wrapper-module:47:9)
  75 | function enforceLanguageTag(unsafeLanguageTag) {
  76 |     return () => {
> 77 |         const tag = unsafeLanguageTag()
     |                    ^
  78 |         if(!isAvailableLanguageTag(tag)) {
  79 |             throw new Error(`languageTag() didn't return a valid language tag. Check your setLanguageTag call`)
  80 |         }

**Comment by samuelstroschein** [comment]
Thanks for the report. A PR is warmly welcome and will be reviewed and merged asap

**Comment by JeffWScott** [comment]
Is this why I cannot test my translations by simply changing the browser language?

**Comment by samuelstroschein** [comment]
@amazfs @JeffWScott are you on the latest version ? 

the headers are awaited https://github.com/opral/monorepo/blob/9496966134a9f71aab6cfa70cc4ae63a4e7e4868/inlang/source-code/paraglide/paraglide-next/src/app/getLanguage.server.ts#L14

**Comment by JeffWScott** [comment]
@samuelstroschein 

I didn't see the "-next" in the issue heading.  I'm using "paraglide-sveltekit" not next.

I see you responded to my issue for that 
https://github.com/opral/inlang-paraglide-js/issues/269

Thanks

**Comment by samuelstroschein** [comment]
@amazfs please confirm if using paraglide-next `^0.7.1` solves this issue

**Comment by samuelstroschein** [comment]
great to hear. closing this issue

**Comment by jorrit** [comment]
@samuelstroschein In 0.7.9 `headers()` is not awaited. I can't find the current source code of `getLanguage.server.ts` on Github, but this is in my local copy:

```
        const langHeader = (headers()).get(PARAGLIDE_LANGUAGE_HEADER_NAME);
```

**Comment by samuelstroschein** [comment]
@jorrit that is expected https://github.com/opral/inlang-paraglide-js/issues/245#issuecomment-2608727658
