### ISSUE TITLE
Paraglide with sveltekit output source function content instead of the end result translation

### ISSUE THREAD

**Issue by function1983** [opral/inlang-paraglide-js#268]
Hi, thanks for the awesome project.

I have Sveltekit (Svelte 5).

In `+page.svelte`:
```
import * as m from '$lib/paraglide/messages.js';
...
<div>{m.no_items_found}</div>
```
Output will be:
```
(params = {}, options = {}) => { return { de: __vite_ssr_import_2__.no_items_found, en: __vite_ssr_import_1__.no_items_found }[options.languageTag ?? __vite_ssr_import_0__.languageTag()](); }
```
I checked de.json and en.json both have `no_items_found`. Helper text in vscode shows the correct text.

Other items work well for some reasons.
Can you point me to where the problem might be?
Thank you.

**Comment by samuelstroschein** [comment]
Did you forget to call the function? 

```diff
-<div>{m.no_items_found}</div>
+<div>{m.no_items_found()}</div>
```

**Comment by function1983** [comment]
> Did you forget to call the function?
> 
> ```diff
> -<div>{m.no_items_found}</div>
> +<div>{m.no_items_found()}</div>
> ```

Indeed it is. It bugs the hell out of me. I blame it on the helper text. :P . Thank you so much.
![image](https://github.com/user-attachments/assets/c4ddb0b0-4513-42ca-8925-3c1ee67c0784)
