### ISSUE TITLE
404 Error for URLs with Uppercase Letters Using Paraglide-SvelteKit

### ISSUE THREAD

**Issue by ambigos1** [opral/inlang-paraglide-js#275]
Hi.
I am using the Paraglide-SvelteKit library

I am getting a 404 error in case one letter in the URL contains Uppercase.

for example, The following URL throws a 404 error:
[https://instblast.com/instagram/free-Instagram-followers](https://instblast.com/instagram/free-Instagram-followers)

because the **I**nstangram word containing "I" as uppercase

However, this URL works as expected:
[https://instblast.com/instagram/free-instagram-followers](https://instblast.com/instagram/free-instagram-followers)

In the hooks.ts I wrote:
import type { Reroute } from '@sveltejs/kit';
import { i18n } from "$lib/i18n";
export const reroute: Reroute  = i18n.reroute() 

as documented.

Dev dependencies:
		"@inlang/cli": "^2.18.1",
		"@inlang/paraglide-js": "^1.11.3",
		"@sveltejs/adapter-static": "^3.0.6",
		"@sveltejs/kit": "^2.9.0",
		"@sveltejs/vite-plugin-svelte": "^3.1.1",

Dependecies:
"@inlang/paraglide-sveltekit": "0.11.5",

Do you have any suggestions on how to solve this issue?

**Comment by samuelstroschein** [comment]
This is SvelteKit behavior, unrelated to Paraglide JS. <br><br>You can test this by opening the svelte.dev site. Opening [https://svelte.dev/tutorial/svelte/welcome-to-svelte](https://svelte.dev/tutorial/Svelte/welcome-to-svelte) but opening [https://svelte.dev/tutorial/Svelte/welcome-To-svelte](https://svelte.dev/tutorial/Svelte/welcome-To-svelte) where the T in welcome-to-svelte is capitalized leads to a 404. 

I recommend opening an issue in SvelteKit if you believe that case sensitivity in URLs is wrong.

**Comment by ambigos1** [comment]
@samuelstroschein 
Thanks for your answer.
just submitted an issue in svelte-kit

https://github.com/sveltejs/kit/issues/13198

**Comment by ambigos1** [comment]
Hi @samuelstroschein 
This is the following response I got
https://github.com/sveltejs/kit/issues/13198#issuecomment-2553215031

// src/hooks.ts
export function reroute({ url }) {
  // this will convert /abouT to /about and match the /about/+page.svelte route
  return url.pathname.toLowerCase();
}

My question is how can I implement it on hooks.ts when I am using i18n.reroute()?
export const reroute: Reroute  = i18n.reroute()

Thanks.

**Comment by samuelstroschein** [comment]
wrap the reroute. 

_this is a pseudocode example. to illustrate wrapping. will likely need adjustments._

```ts
export const reroute: Reroute = (args) => {
  args.url = url.pathname.toLowerCase()
  return i18n.reroute(args)
 }


```

**Comment by ambigos1** [comment]
This is not working.
i18n.reroute() Expected 0 arguments

**Comment by samuelstroschein** [comment]
try 

```
export const reroute: Reroute = (args) => {
  args.url = url.pathname.toLowerCase()
  return i18n.reroute()(args)
 }
```

why

the i18n.reroute() hook creates the reroute. should ideally be called `i18n.createReroute()` instead

*Please figure out the rest yourself. I can't provide support for syntax, or Paraglide unrelated questions.*

**Comment by ambigos1** [comment]
No matter how much I tried in multiple ways this bug keeps happening.

This bug is likely related to inlang or something.
@samuelstroschein  can you please ask one of the inlang developers to look at it?

the last code I have tried is:

/** @type {import('@sveltejs/kit').Reroute} */
export function reroute({ url }) {
	url.pathname = url.pathname.toLowerCase();
	return i18n.reroute()({ url });
}

And still, I am getting a 404 error

**Comment by samuelstroschein** [comment]
Provide a minimal reproduction repository and I can look into it. Highly unlikely that it's due to Paraglide.
