### ISSUE TITLE
firebase - @sveltejs/adapter-static - refresh not working

### ISSUE THREAD

**Issue by HBartolin** [opral/inlang-paraglide-js#276]
I have SvelteKit app. It host on https://firebase.google.com/ with @sveltejs/adapter-static. When you refresh page with not default language (sourceLanguageTag) you get error: "Failed to load module script: Expected a JavaScript module script but the server responded with a MIME type of "text/html". Strict MIME type checking is enforced for module scripts per HTML spec.".

"@sveltejs/adapter-static": "^3.0.6",
"@sveltejs/kit": "^2.12.1",
"svelte": "^5.14.4",
"typescript": "^5.7.2",
"@inlang/paraglide-sveltekit": "^0.15.0",
"firebase": "^11.1.0"

**Comment by samuelstroschein** [comment]
Can you provide a minimal reproduction? <br><br>I suspect SvelteKit internals to be an issue or Paraglide SvelteKit's usage of rerouting in SvelteKit. But, not Paraglide JS itself given that Paraglide JS emits JS code and is not responsible for bundling and serving the code.

**Comment by HBartolin** [comment]
U can find it here: https://github.com/HBartolin/yy 

Local everything works, on Firebase dont. I don't know how it test without Firebase?
