### ISSUE TITLE
Set language programmatically

### ISSUE THREAD

**Issue by DeltaLaboratory** [opral/inlang-paraglide-js#286]
Can I disable localized routing and use only local storage and accept-language header with sveltekit?

**Comment by samuelstroschein** [comment]
yes if you use [paraglide js](https://inlang.com/m/gerre34r/library-inlang-paraglideJs) without the sveltekit adapter. 

I will write a guide in the next few weeks. In the meantime, here is a reply Loris gave on Discord. 

**Installing** Start by installing `paraglide-js` with 

```
npx @inlang/paraglide-js@latest init
```

 This will create all the files you need to use paraglide. You can then edit your messages in `messages/[lang].json` (should have been automatically created). When you've made your changes, run the compiler like so: 

```
npx @inlang/paraglide-js@latest compile --project ./project.inlang
```

 This will generate `src/paraglide/messages.js`, which contains all your messages. Import your messaegs from there: 

```
<script>
  import * as m from "./paraglide/messages.js"
  m.hello_world()
</script>
```

 You probably don't want to run the command manually everytime, so you can instead install the `@inlang/paraglide-vite` plugin. **Switching Languages** You can set the language with the `setLanguageTag("de")` function exported from `src/paraglide/runtime.js`. By default this will **not** rerender any messages that have already been rendered. Messages are just functions, they have no reactivity built-in. Instead, you will need to trigger a rerender manuall. In your `root.svelte`, use the `onSetLanguageTag` function to react to the language changing and rerender: 

```
<script>
  import { setLanguageTag, onSetLanguageTag } from "./paraglide/runtime"
  import App from "./app.svelte"
  let lang = "de"
  // set initial language
  setLanguageTag(lang)

  // react to language changes
  onSetLanguageTag(newLang => lang = newLang)
</script>

{#key lang}
 <App/>
{/key}
```

**Comment by DeltaLaboratory** [comment]
Thank you! It works well.
