### ISSUE TITLE
Staggered Plural Rollout

### ISSUE THREAD

**Issue by LorisSigrist** [opral/inlang-paraglide-js#34]
## Problem

Supporting Plurals would give Paraglide an advantage in i18n library comparisons, as it's another box ticked.

The SDK is already capable of supporting plurals. What's needed is plugin support & for Inlang apps to support it.

We haven't gone ahead yet to avoid \\*ecosystem skew\\*, where some apps support it & others don't. For plurals this skew would be acceptable IMO.

## Proposal

We only need support for plurals in the inlang-message-format, not all plugins. Once message-persistence is ready that's a mute point anyways.

I'm proposing to roll out plurals in *one* plugin + Paraglide first, learn lessons from there & then expand support across the ecosystem down the line.

There is an experimental implementation ready to try:
[https://github.com/opral/monorepo/pull/2376](https://github.com/opral/monorepo/pull/2376)

This was discussed with @loris.sigrist, @nils.jacobsen, @niklas.buchfink and @jannes.blobel in Around
[https://mail.missiveapp.com/#inbox/conversations/0ee90b38-621c-4b69-b739-c3dbbcfd3746](https://mail.missiveapp.com/#inbox/conversations/0ee90b38-621c-4b69-b739-c3dbbcfd3746)

**Comment by NilsJacobsen** [comment]
I've always been a big fan of small PRs and early merges.

**Comment by LorisSigrist** [comment]
> use the default template

Is there a way to get the template in Linear? 

> Wait for the SDK where one person is responsible on a longer running project for rolling out variants across the ecosystem

The SDK already supports Variants, we just don't use them. There would be zero code-changes required from the SDK

**Comment by LorisSigrist** [comment]
> Can this be closed in favor of [variants (pluralization, gender, a/b test)](https://linear.app/opral/project/variants-pluralization-gender-ab-test-35eb35cc7215)

Yes
