### ISSUE TITLE
Get Used in Starter-Kit Repository

### ISSUE THREAD

**Issue by LorisSigrist** [opral/inlang-paraglide-js#39]
## Context/Problem

Most starter-kits either don't have i18n or use some flavor of i18next. Starter kits are "superspreader" repos as hey get replicated into many projects.

## Proposal

Find a bunch of starter-kits that \\\*\\\*don't have i18n yet and add Paraglide + Sherlock.

* [https://github.com/Skolaczk/next-starter](https://github.com/Skolaczk/next-starter) (PR made)
* [https://app.opire.dev/home?search=documenso](https://app.opire.dev/home?search=documenso)
* [https://docs.landingbud.com/](https://docs.landingbud.com/)

> We should be the ones introducing i18n. It's really hard to get template-repos to switch once they've chosen a library.

**Comment by samuelstroschein** [comment]
Closing as nice to have
