### ISSUE TITLE
paraglide js doens't find repo root

### ISSUE THREAD

**Issue by samuelstroschein** [opral/inlang-paraglide-js#44]
## Problem

Paraglide triggers lix "no repo found" warning even though a repo exists.

### Additional information

Is paraglide using `findRepoRoot` finding a repo root?

```
const repo = await openRepository(await findRepoRoot())
```

**Comment by LorisSigrist** [comment]
I just checked and paraglide already uses `findRepoRoot` in all places where a repo is opened

**Comment by samuelstroschein** [comment]
okay, then `findRepoRoot` is buggy
