### ISSUE TITLE
Astro integration - languageTag() is wrong on build

### ISSUE THREAD

**Issue by dallyh** [opral/inlang-paraglide-js#45]
There seems to be an issue with building for SSG and using languageTag() in the Astro integration. Dev server works fine, however on build the languageTag() always returns the default language tag set in the config.

I have created a simple repository here: [https://github.com/dallyh/language-tag-issue-example](https://github.com/dallyh/language-tag-issue-example).

This is the output of the build:

```
generating static routes 01:05:49 ▶ src/pages/[...lang]/404.astro 01:05:49 
├─ /404.html...Locale from page: cs ...Locale from layout: cs  (+8ms) 01:05:49 
└─ /en/404/index.html...Locale from page: cs ...Locale from layout: cs  (+3ms) 01:05:49 
✓ Completed in 24ms.
```

The logs in console for locales are from `src/layouts/MainLayout.astro` and page `src/pages/[...lang]/404.astro`. `getStaticPaths()` is used to generate the static routes.

I can reproduce this bug only on my machine which runs Windows, if I open the repository in StackBlitz, run npm install and npm build, the outputs are different. I'm out of ideas of what could be causing this. Please see the screenshot below, where on the left there is a StackBlitz IDE and on the right a simple windows Command Line.

![image](https://uploads.linear.app/4cb6d418-86ee-4425-b5c8-f91266b0ab28/f4d51ade-ec91-49be-b128-931daeec1f0c/9d5b114f-1686-4c14-a594-b0d73bc4d484?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzRjYjZkNDE4LTg2ZWUtNDQyNS1iNWM4LWY5MTI2NmIwYWIyOC9mNGQ1MWFkZS1lYzkxLTQ5YmUtYjEyOC05MzFkYWVlYzFmMGMvOWQ1YjExNGYtMTY4Ni00YzE0LWE1OTQtYjBkNzNiYzRkNDg0IiwiaWF0IjoxNzExNDEyMDk2LCJleHAiOjMzMjgxOTcyMDk2fQ.MFtOWUroPDaXWTlzQVOWwZf5OPAEUYKZj0t29n_y0ao)

**Comment by dallyh** [comment]
Just to be sure I ran the same on my work laptop, which uses Windows 11, and on my Linux laptop, which runs Debian 12. On the Windows laptop the output is like this:

![image](https://github.com/opral/inlang-paraglide-js/assets/6968534/aa01bdb9-23a8-49f3-879a-9e102fc3b03d)

**Comment by LorisSigrist** [comment]
I unfortunately don't have access to a windows machine to debug this, but I suspect this is likely caused by a bug in the built in `astro:i18n` package. `languageTag()` is supposed to just return `Astro.currentLocale` when used in `.astro` files. 

Could you try the following & see if the issue persists:

1. Remove the paraglide integration
2. Replace `languageTag()` in `MainLayout.astro` with `Astro.currentLocale`
3. Run the build & see if the issue persists

**Comment by LorisSigrist** [comment]
I'm able to reproduce this. Thanks for the repo! I also had to switch to windows, which is very odd

**Comment by dallyh** [comment]
@LorisSigrist You're fast! I tried it with `Astro.currentLocale` and it returns the correct locale.

```astro
---
const locale = Astro.currentLocale;
console.log("...Locale from layout: " + locale);

---

<!doctype html>
<html lang={locale}>
    <head>
    </head>
    <body>
    </body>
</html>
````

```
generating static routes 
10:20:37 ▶ src/pages/[...lang]/404.astro
10:20:37   ├─ /404.html...Locale from page: cs ...Locale from layout: cs (+17ms)
10:20:37   └─ /en/404/index.html...Locale from page: en ...Locale from layout: en(+11ms)
10:20:37 ✓ Completed in 71ms.

```

**Comment by LorisSigrist** [comment]
Thanks! I got access to a windows machine via Shadow PC & am getting the same result. I'll need to investigate some more to find out why this is happening. `languageTag()` is just supposed to be an alias for `Astro.currentLocale` when called from `.astro` files.

**Comment by LorisSigrist** [comment]
More progress, although I'm not sure it's good news. 

The adapter correctly identifies the language it's supposed to use, but for some reason the call to `setLanguageTag` doesn't work on windows. I know its identifying the correct language because `Astro.locals.paraglide.lang` get's set correctly. 


Debugging this online on a Shadow-PC sucks, but it is what it is 😅

**Comment by dallyh** [comment]
Hey thanks for the effort! In the meantime I've found out that every built page is not localized properly, but that is probably a consequence of `setLanguageTag` not working.

Fortunately I'm building the site on Cloudflare which uses Linux workers, and I can still spin up my Linux laptop and or develop on Windows under WSL.

Still though, it's an inconvenience and it could potentionaly create some more issues.

There is one workaround which involves doing this on every page and component, but it defeats one of the features of the adapter :(

```ts

const locale = Astro.currentLocale;
setLanguageTag(locale);

```

**Comment by LorisSigrist** [comment]
Pretty sure this is it. When logging out all the module-ids that vite loads there is one import for the runtime with backslashes and one with forward slashes. What a silly bug
