### ISSUE TITLE
[Bug] "Repo url is required, use file:// for local repos" on local MacOS initialization

### ISSUE THREAD

**Issue by gab2405** [opral/inlang-paraglide-js#47]
Whenever I try to initialize the plugin, I get the error message:

"Error: repo url is required, use file:// for local repos"

Steps to reproduce:

- Setup a new project
- Run "npx @inlang/paraglide-js@latest init"

Node Version:
v20.9.0

NPM Version:
10.1.0

OS:
MacOS 14.4

**Comment by samuelstroschein** [comment]
this being fixed atm. @jan.johannes looking forward to the release of the adjusted lix warning handling

**Comment by janfjohannes** [comment]
@samuelstroschein  this is a completely different error message than what we talked about yesterday.

**Comment by LorisSigrist** [comment]
I'll take a look

**Comment by janfjohannes** [comment]
@LorisSigrist  i see you allready fixed the one case in paraglide where file:// was missing. maybe its just an outdated library?

**Comment by LorisSigrist** [comment]
Pretty sure I see what this is. If a repo **is** found the current code doesn't prefix the path with `"file://"` & just uses the path itself. This conflicts with the stricter validation in `openRepository`. Should be a quick fix

**Comment by janfjohannes** [comment]
@LorisSigrist  but findRepoRoot allready prefixes file://  . what place in code do you mean?

**Comment by LorisSigrist** [comment]
In that case I'm not sure. Will do some debugging

**Comment by LorisSigrist** [comment]
This should be fixed in `@inlang/paraglide-js@1.3.5` that's about to release. 
The change that added the `file://` prefix wasn't pushed out properly.

**Comment by janfjohannes** [comment]
ahhh thats exactly what i thouhgt
