### ISSUE TITLE
SvelteKit url matchers with Translated paths

### ISSUE THREAD

**Issue by runar-rkmedia** [opral/inlang-paraglide-js#52]
If setting up translated paths as in desribed in https://inlang.com/m/dxnzrydw/library-inlang-paraglidejsadaptersveltekit#translated-paths it does not work with matchers https://kit.svelte.dev/docs/advanced-routing#matching

```typescript
export const i18n = createI18n(runtime, {
  defaultLanguageTag: 'nb',
  pathnames: {
    '/Case': {
      en: '/case',
      nb: '/sak',
    },
    '/Case/[ID=integer]': {
      en: '/case/[ID=integer]',
      nb: '/sak/[ID=integer]',
    },
    '/Case/New': {
      en: '/case/new',
      nb: '/sak/ny',
    },
  },
})
```

Here, the `/en/case/new` and `/sak/ny` links are rewritten in `a href`'s, but they result in 404s

If I change the url in the code to for instance `/en/newcase` and `/newsak` respectively, it works.

`/Case/New` works in all conditions.

**Comment by awbx** [comment]
I am encountering the identical issue.

**Comment by LorisSigrist** [comment]
Hi! As stated in the docs, currently only simple params are supported. This means: no matchers, no wildcard segments and no optional segments. 

This limitation is something we will be fixing soon
