### ISSUE TITLE
Update Adapter Docs to be Standalone

### ISSUE THREAD

**Issue by LorisSigrist** [opral/inlang-paraglide-js#64]
## Context

The Adapter pages have higher search-intent than the main Paraglide page. Ideally people should find everything they need on the adapter page, without having to refer to the Paraglide main page.

## Proposal

Update the Adapters pages so they do all the onboarding themselves

**Comment by NilsJacobsen** [comment]
You could also check if there is some keyword tuning potential for "<stack> i18n" google search term.
