### ISSUE TITLE
Use Index access instead of `.at()` function to support legacy browsers

### ISSUE THREAD

**Issue by testvinder** [opral/inlang-paraglide-js#78]
We are seeing a lot of errors in Sentry from users with older Macs / Safari versions. It is due to the at() function not being available in older browsers. It is specifically this parts that causes the error.
```
        getLanguageFromUrl(url) {
            const pathWithLanguage = url.pathname.slice(normaliseBase(base).length);
            const lang = pathWithLanguage.split("/").filter(Boolean).at(0);
            if (runtime.isAvailableLanguageTag(lang))
                return lang;
            return defaultLanguageTag;
        },
```

Could you consider using traditional index access instead so it works for both older and newer browser?

**Comment by testvinder** [comment]
You can see the browser compatibility here:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/at#browser_compatibility

Safari added it on 2022-03-14 and everyone else before that so it is well supported, but we see quite a bit of traffic from Mac users running older versions. It would be great if you could change it.

**Comment by LorisSigrist** [comment]
Done in https://github.com/opral/monorepo/pull/2588
