### ISSUE TITLE
Compile t10s into multiple files

### ISSUE THREAD

**Issue by nikita-zalesskiy** [opral/inlang-paraglide-js#80]
### Problem

At the moment Paraglide does not support namespaces and multiple files for t10s. In general, such approach becomes difficult to maintain.

### Proposal

It would be nice to see an ability to use `pathPattern` or another config variable to specify a filename for compiled messages.

### Example

Config:
```json
{
  "$schema": "https://inlang.com/schema/project-settings",
  "sourceLanguageTag": "en",
  "languageTags": [
    "en",
    "de"
  ],
  "modules": [
    "https://cdn.jsdelivr.net/npm/@inlang/plugin-json@latest/dist/index.js"
  ],
  "plugin.inlang.json": {
    "pathPattern": {
      "homepage": "./i18n/{languageTag}/homepage.json",
      "about": "./i18n/{languageTag}/about.json"
    }
  }
}
```

Generated files:
```
- project.inlang
 - messages
  - homepage.js
  - about.js
```

Usage:
```javascript
// Svelte-like import.
import * as about from "$paraglide/messages/about.js";
import * as homepage from "$paraglide/messages/homepage.js";

const aboutName = about.name();
const homepageName = homepage.name();
```

**Pros**

- improvement is safe in terms of "breaking of tree-shaking".
- improved DX because of smaller files with shorter keys. 
- improved IntelliSense as we import t10s files we want.

**Cons**

- possible implementation efforts.

**Comment by LorisSigrist** [comment]
Namespaces are not something we want to pursue at the moment. Introducing They throw up a lot of questions & don't provide a sufficient benefit in our view.
- How would you interact with namespaces from tools like the [Sherlock IDE Extension](https://inlang.com/m/r7kp499g/app-inlang-ideExtension), the [Parrot Figma Plugin](https://inlang.com/m/gkrpgoir/app-parrot-figmaPlugin), or the [Fink Localization editor](https://inlang.com/m/tdozzpar/app-inlang-finkLocalizationEditor)?
- Doesn't provide a meaningful advantage in terms of lazy-loading / tree-shaking. Paraglide's messages are already tree-shaken so the exact same code would be shipped (after bundling & minification) both with and without namespaces.


In general, Inlang takes the stance that you shouldn't really bother to organise your translations & instead just create them ad-hoc. That's how most large companies do it; it _is_ a sustainable approach. 
- Fuzzy-search for existing messages
- Whenever you need a message, just create a new one. The [Sherlock IDE Extension](https://inlang.com/m/r7kp499g/app-inlang-ideExtension) makes this very convenient. 
- Provide a meaningful name, using underscores to separate words: `about_page_title`

**Comment by fxmb** [comment]
Just following up here: Am I expected to put ALL my translation in one single message file? Doesnt that get extremely messy over time? Is there no way to organize messages by folders?

**Comment by yorrd** [comment]
I appreciate the notion of just having a big mess of a translation file because otherwise finding a structure for the translation keys is redundant information. Love this approach. 

Just as a heads up for Googlers: you can set up a monorepo or some kind of structure that compiles modules and compile them separately. Arguably if your translation file gets huge, this should be done anyways. Then there are also fewer messages in one module and scoping is achieved. Of course that's not a solution for every scenario but this is working well for our team.
