### ISSUE TITLE
Get Paraglide / Paraglide Next Adapters mentioned in i18n Blogs

### ISSUE THREAD

**Issue by LorisSigrist** [opral/inlang-paraglide-js#83]
### Context

There are many popular and well-ranking blog posts that basically just list i18n libraries you might use

### Proposal

Use AHREFs to find the most influential ones & contact the authors to give paraglide a try. Suggested by @nils.jacobsen and @niklas.buchfink

**Comment by samuelstroschein** [comment]
closing as nice to have. current prio is paraglide js 2.0 release
