### ISSUE TITLE
`paraglide-next init` support Pages Router Setup

### ISSUE THREAD

**Issue by LorisSigrist** [opral/inlang-paraglide-js#91]
### Context

Currently `paraglide-next init` only supports setting up the App router, not the Pages router. This causes a de-sync between the setups drastically increasing the documentation effort.

### Proposal

Also make it work for Pages routers

**Comment by samuelstroschein** [comment]
wou;dn't this be part of a `pages router` milestone?

**Comment by LorisSigrist** [comment]
"Simplified Onboarding Flow" seems to be the most descriptive. I don't plan on spending much time on the Pages router since it's legacy so I don't think having a whole separate milestone makes sense. <br><br>This issue exists to avoid users immediately getting an error when trying `paraglide-next` in their project. That's a bad first impression. Apart from that no pages router improvements are planned.
