### ISSUE TITLE
Is sourceLanguageTag optional?

### ISSUE THREAD

**Issue by juliomuhlbauer** [opral/inlang-paraglide-js#94]

**Comment by LorisSigrist** [comment]
This question could refer to several things.

Having a `sourceLanguageTag` defined in `project.inlang/settings.json` is not optional as it's vital for the language fallback logic. 

By default, the `sourceLanguageTag` is also the default Language, which does not need to be included in the url-path
- `/about` -> about page in default language
- `/en/about` -> also valid, even if `en` is the default language

**Comment by LorisSigrist** [comment]
FIY for general usage-questions it's better to ask in Inlang's discord server. You'll get a response much quicker

[https://discord.gg/gdMPPWy57R](https://discord.gg/gdMPPWy57R)
