### ISSUE TITLE
Update OG images for new Package Names

### ISSUE THREAD

**Issue by LorisSigrist** [opral/inlang-paraglide-js#95]
### Context

The OG images on the framework packages still include the old adapter names 

### Proposal

Update them to the new ones

**Comment by NilsJacobsen** [comment]
Just to check in on that: You also think that dynamic og images based on title and description for every inlang item make sense, right?

**Comment by LorisSigrist** [comment]
In general yes, that would be preferable to the single OG image we currently have.

However, for Apps like Paraglide or Fink it will likely make more sense to have custom OG images. It's an opportunity to stand out on Social Media

**Comment by NilsJacobsen** [comment]
Alright. Thanks for the info:)
