### ISSUE TITLE
`@inlang/paraglide-js init` does not properly resolve `tsconfig`

### ISSUE THREAD

**Issue by hmnd** [opral/inlang-paraglide-js#99]
## Description

The check for `"moduleResolution": "Bundler"` does not properly resolve the `extends` field of the project's `tsconfig.json`, thus reporting an error if the user already has that setting set in a tsconfig that the project extends.

## Example

`tsconfig.base.json`

```json
{
  "compilerOptions": {
    "moduleResolution": "Bundler"
  }
}
```

`tsconfig.json`

```json
{
  "extends": ["./tsconfig.base.json"]
}
```

**Comment by LorisSigrist** [comment]
Thanks!<br><br>Which behavior would you prefer from the `init` CLI?

* Paraglide should try to follow the `extends` to make sure the tsconfig is correct
* If an `extends` is present it should still prompt if the setting are set, but not actually enforce it
* It an `extends` is set it should just move on
